### ISSUE TITLE
Readnoise monitor info for NRS2 detector is empty

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1104]
The plots output by the readnoise monitor are currently populated for NRS1, but empty for NRS2. 

Check to see if something has gone wrong.

**Comment by york-stsci** [comment]
As far as I can see, nothing has gone wrong. The NIRSpecReadnoiseStats table contains 6 entries (each entry covering a single input file). All of them are NRS1 files. So the issue is just that the read noise monitor hasn't made it to NRS2 yet. Presumably it will at some point. Right now it's working on some new MIRI data.

**Comment by bhilbert4** [comment]
Readnoise data for both detectors is now populated. Closing.
