### ISSUE TITLE
Copy new bad pixel monitor html files to pljwql1

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1221]
The bad pixel monitor has been revised such that it saves a separate html file for each instrument into the templates directory. When a user requests the bad pixel monitor page for a given instrument, this html file is read in and displayed. 

However, if the bad pixel monitor will now be run on pljwql2, we'll need a way to copy the results into the directory for pljwql1 so that the web app can display them. 

Perhaps a cron job? 
@york-stsci what do you think the best method would be to keep pljwql1 up to date?

**Comment by york-stsci** [comment]
I don't think there's any current intention to move monitors to another server, other than temporarily under specific circumstances. That said, my hope is that we will, eventually, be able to do so if we need to. As such, yes, if we're generating HTML files, we will want some way to synchronize them. My immediate thought is that, when one is generated, it should be copied to central storage (deleting whatever it's replacing), and before generating a new one the monitor can look at central storage to see if there's already one that's recent enough and, if there is, retrieve that one rather than coping its own. That would require developing some sort of criteria for figuring out whether you need to generate a new output file, but presumably the one that's only operating on pljwql1 already has to do that.

**Comment by bhilbert4** [comment]
Ok. For some reason I thought monitors were all running on pljwql2. So I guess this is something we can deal with if we ever move the monitors away from pljwql1. So I think the problem I ran into this morning was just that the bad pixel monitor has not run on any new data since the updates were merged a couple weeks ago, and therefore the html files the web app was looking for didn't exist. I copied over initial versions of the html files from the test server this morning, so that the app doesn't crash anymore. 

So I'll close this for now, and we'll have to remember to deal with these html files if the monitors ever move to another server.
