### ISSUE TITLE
Explore using Docker

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#200]
I wonder if we could use Docker to make the packaging and installation of `jwql` easier for users

**Comment by laurenmarietta** [comment]
Here is an instructive talk from DjangoCon explaining the basics of Docker - could be useful:
https://www.youtube.com/watch?v=qsEfVSTZO9Q

**Comment by bourque** [comment]
Thanks @laurenmarietta, that was a very informative! I'm going to try my hand at implementing something.

**Comment by laurenmarietta** [comment]
Potentially useful O'Reilly resource about Docker:
https://learning.oreilly.com/videos/learning-docker/9781491956885/9781491956885-video244778

**Comment by bourque** [comment]
I found this resource to also be quite helpful: https://semaphoreci.com/community/tutorials/dockerizing-a-python-django-web-application

**Comment by JeffValenti** [comment]
FYI, ITSD did not allow me to install Docker on my JWST-funded laptop, due to security concerns (additional ports need to be enabled). Instead they created a VM with Docker for me to use. Not sure why that was deemed OK. In order to use Docker commands, ITSD gave me sudo privileges for the docker command. Ugly. Getting data in and out of Docker <--> VM <--> local machine required lots of typing and frequent 2FA. Not fun. ITSD is pondering whether there is a better approach. Probably my workflow could be improved as well. If the user interface is only via a web application, then perhaps the use of docker would be transparent to the user. However, at this point my naive impression is that conda is much simpler and hence better than docker, as long as conda provides the functionality required. For now I have abandoned Docker for my personal research project.

**Comment by bourque** [comment]
Thanks @JeffValenti, that is good to know.  When talking with @alexyermolaev who was helping to set up our development web server, he had mentioned that the process would have been "easier if I had a docker container", and so that prompted me to go down that road.  I have a primitive working example (#297) that may or may not be used to help us set up a production web server (#294), but that will be up to ITSD I suppose on whether or not they want to use it.  This is all to say -- hopefully ITSD will give some further guidance on if and how these docker containers can be used effectively for this use case.

**Comment by bourque** [comment]
As we move towards a solution that uses ASB infrastructure (#294), it appears that Docker is not going to be needed, so I am closing this issue for now.
