### ISSUE TITLE
Expand filesystem monitor to keep track of JWQL central storage area

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#361]
The JWQL central storage area will store the preview images and thumbnails needed for the web app, along with any other data the team may need.  It would be helpful to have a grasp on how much space we are using and have available to us in this area.

**Comment by cracraft** [comment]
For this update, we're only looking to add a single plot for the preview_images area and one for the thumbnails area that list the total space being used compared to what is available? Are there any other areas that need to be tracked, and should we just add these to the already established database or set up a new db instance with the two values vs. date? Are we also tracking space used in logs/outputs, etc., and if so, do you just want all the individual locations added up to say we're using this much space and have this much available, adding only one summed plot to the dashboard?

**Comment by bourque** [comment]
@cracraft I think the monitor should just be keeping track of the `size`, `used`, and `available` for each of the following areas:

- the top level directory of the central storage area, i.e. what is returned by `utils.utils.get_config()['jwql_dir']`.
- the main subdirectories (sans `filesystem` since that is treated separately):
    - `logs/`
    - `outputs/`
    - `test/`
    - `preview_images/`
    - `thumbnails/`

I envision that we could set up a separate database table for this (perhaps call it `central_storage`), and have columns for `date`, `area` (storing values such as `all`, `logs`, `outputs`, etc.), `size`, `used`, `available`.  

The corresponding plot could plot the `size`, `used`, and `available` for each of these areas on the same plot.  Note that `size` and `available` will only need to be plotted for `all`, since it should be the same value for each area.

**Comment by cracraft** [comment]
Matthew, I've been working on this one and have the script calculating the directories using your df method. However, it's not giving accurate results. According to df, all of the directories are the same size. Obviously, this is not correct. I think I remember running into this when I was writing the script originally, and was the reason I didn't use df as my filesystem size counting method in the first place.

**Comment by cracraft** [comment]
As was pointed out to me, df commands give you the whole disk, so that wouldn't be the right command for different directories. Guess I'm going to end up doing another counting all file sizes in each directory again for each directory.

**Comment by cracraft** [comment]
I think I figured out the file size issue, but now there's another question. I got the script to run up through all the file counting stats, and it took 2.5 hours to run. The upper level jwql directory was 1.5 hours. Of the 8 TB disk size that df shows, that directory is almost 2 TB. And the os.walk went through every file. This jwql directory also contains the filesystem, as well as logs, preview_images, etc. This run time will only increase when we start putting real data into it and running all of the monitors. Thoughts?

**Comment by laurenmarietta** [comment]
Great sleuthing! Glad you were able to figure out the size problem. What did the issue end up being?

Not such good news about the timing, though... I personally find it surprising that it takes that long. What function did you end up using to get the directory sizes and usage stats? 

Also, since you have functional code, it might be worthwhile to open a WIP pull request now. That would also make it easier for us to see what's happening in the script, and say if there's any way we can think of to speed it up.

**Comment by cracraft** [comment]
I did some testing on a local disk and found that if we take the df stats using the -k option to put it in blocks of 1024 bytes rather than the default of 512, then divide by 1024^3 rather than the 4th, we can get consistent numbers. However, I still had issues getting any of the usage scripts that were python specific working on our central store directories, so I'm sticking with df and hoping that's at least somewhat consistent. 

As for the timing issue, the df part to get total/used/available of the disk partition only doesn't take long. What takes a long time is the os.walk through each of the directories, counting up the sizes of every file in the directory/subdirectories. There is some duplication of the counting right now that I have a plan to eliminate, but that hasn't been coded in yet. However, any os.walk of all the files is going to be slow, especially as the directories grow.

**Comment by bourque** [comment]
See #401
