### ISSUE TITLE
EDB mnemonic query plot blank on local server

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#425]
@Johannes-Sahlmann and I have both noticed that, when the web app is being run on a local server, the EDB mnemonic query `bokeh` plot does not appear:
<img width="1520" alt="Screen Shot 2019-05-22 at 9 25 05 AM" src="https://user-images.githubusercontent.com/12650803/58178083-81117900-7c73-11e9-8328-31b7260b82bd.png">
I personally see this behavior on every branch - feature branches, `develop`, and `master`.

Good news is, I don't see this bug on the development server (dljwql.stsci.edu). This suggests to me that it has something to do with running the local Django server? 

If anyone else has seen this, please share.

**Comment by bourque** [comment]
@laurenmarietta @Johannes-Sahlmann Here is what the javascript console shows when trying to build a plot:

![Screen Shot 2019-06-03 at 15 07 12](https://user-images.githubusercontent.com/2250769/58827570-58916380-8611-11e9-9c56-d2ac9be23f5c.png)

**Comment by Johannes-Sahlmann** [comment]
Do you know how to fix this? Is it something that I need to add to the python bokeh-plot generation code? 
How can I display the javascript console?

**Comment by bourque** [comment]
This appears to be an issue with the version of `bokeh`.  The dev web server is currently running version `1.0.1`, while our current `jwql` environment supports `1.1.0` (the env on the dev server has to be manually updated since it is installed in a very specific place, hence why it is out of date).  When i downgraded my local version to `1.0.1` I was able to render a plot with no error messages from the javascript console.

Reading the error message, it seems that we might be able to get this working in version `1.1.0` if we declare `Plot.center` somewhere in the code(?) (I'm not exactly sure what this means).

**Comment by bourque** [comment]
@Johannes-Sahlmann Using chrome, you can go to View > Developer > JavaScript Console.

**Comment by bourque** [comment]
@Johannes-Sahlmann I was able to solve this by simply updating this line to the newer version number:

https://github.com/spacetelescope/jwql/blob/30935d4230a51165d2f0bb7b4305c8d0c13991f4/jwql/website/apps/jwql/templates/base.html#L25

I will put the change in a PR (and make sure it is not breaking anything else)
