### ISSUE TITLE
Fix "Download FITS" and "Download JPEG" buttons in web app

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#768]
With the switch to a MAST-like organized filesystem (#468), the "Download FITS" and "Download JPEG" buttons no longer work in the web app.  These buttons will be (temporarily) removed with #755 since they do not work, but a PR associated with this issue should add them back in and make them work again.

**Comment by bhilbert4** [comment]
Looks like this may be a simple typo?
I think https://github.com/spacetelescope/jwql/blob/develop/jwql/website/apps/jwql/data_containers.py#L383 should point to `path_for_download` rather than `file_for_download`. And the same for line 432.

Would also be nice as part of this to use the mnemonic name as the filename, rather than using the same generic filename in all cases. This way users could download data from more than one mnemonic and not worry about how to keep files organized and prevent overwriting. 

- [x] I can try to incorporate this into #849

**Comment by bhilbert4** [comment]
This issue is larger than just the download button on the EDB page. This is more meant to reference the download buttons on the pages for individual files. The buttons were removed in [755](https://github.com/spacetelescope/jwql/pull/755/files#diff-8928d4de262bc7533ff695b44bf4c19708139fce218acdcb3241a26513cd0411R41)
