### ISSUE TITLE
Create a page containing example anomalies

### ISSUE THREAD

**Issue by aggle** [spacetelescope/jwql#993]
During the MIRI tag-up, we came up with some feature requests to help us check images for quality as they come down:

- A checkbox for each observation to see if it has or has not been reviewed for quality/other issues by an instrument team member.
- Ability to filter observations by date of execution/on archive (or sort by date of execution/on archive) so we can find the new ones.
- In the "Submit Anomalies" box, be able to click on the name of the anomaly and see one or more examples

Thanks!

**Comment by bhilbert4** [comment]
Thanks for the suggestions! 

The checkbox to see if a program has been reviewed (#984) is one of our top priorities. 
Filtering proposals by time is also on our To Do list (#975)

I like the idea of the example anomalies page. I'll update the title of this issue and we can keep it to track an anomaly example page, since the other two suggestions are covered by existing issues.

I think the first step in getting this together will be to gather files with the various anomalies. This seems like something we will need to rely on the instrument teams to provide. From there we can generate jpgs and organize a page or pages to display them.

**Comment by aggle** [comment]
Thanks Bryan! I apologize for not checking the issues page before submitting. I think the Checkbox request is a little different from the issue you link to (#975, "Implement unlooked filter") in the sense that the MIRI team would like something that we can manually tick to confirm that we have _finished_ inspecting it.

**Comment by bhilbert4** [comment]
I think I didn't articulate well enough in #975 what we want to do. Essentially it is as you say. For each image, there will be a box that a user can check when they are done with their examination. Then there will be a filter that can be used on the archive page for a particular instrument, as well as within a given program's page that will show only "new" data. In this case "new" is defined as any image that hasn't had that check box checked. Does that sound like what you're looking for?

**Comment by aggle** [comment]
That’s just what we’re looking for, thanks!

From: Bryan Hilbert ***@***.***>
Reply-To: spacetelescope/jwql ***@***.***>
Date: Wednesday, July 20, 2022 at 11:29
To: spacetelescope/jwql ***@***.***>
Cc: Jonathan Aguilar ***@***.***>, Author ***@***.***>
Subject: Re: [spacetelescope/jwql] Create a page containing example anomalies (Issue #993)


I think I didn't articulate well enough in #975<https://urldefense.com/v3/__https:/github.com/spacetelescope/jwql/issues/975__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!xryR2mu5o6LAbeGSers7SSwTFUNrGoyPDG8ozmO0xHWEOMOgLFotwQMSBC0FVdOskyBAEuSdg_XddPsuKRC5vJJ-Pg$> what we want to do. Essentially it is as you say. For each image, there will be a box that a user can check when they are done with their examination. Then there will be a filter that can be used on the archive page for a particular instrument, as well as within a given program's page that will show only "new" data. In this case "new" is defined as any image that hasn't had that check box checked.

**Comment by bhilbert4** [comment]
The first two bullet points above have been implemented, so this issue is now just about creating example anomaly pages.

I created a branch to start on this yesterday, but as I was walking through jdox and saving images of anomalies, I started thinking "Maybe we should just link to jdox for each of these rather than creating our own pages with content taken from jdox." 

There will probably be some anomalies that are not on JDox, or that are complex enough that we may want to create our own page that contains more than what's on jdox. But my vote would be to link to jdox as much as possible, in order to minimize the pages that we need to maintain. What do you think @mfixstsci?

**Comment by bhilbert4** [comment]
Closing this in favor of a new issue for the example anomaly creation page. Hopefully the new issue will be brought over to Jira. Somehow the bot missed this issue when the Jira project was created.
